<a href="https://colab.research.google.com/github/Crustacean-Hacks/HireEquity/blob/main/models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [ ]:
F_employement= pd.read_csv("Data.csv")

<ipython-input-11-748fc47f9412>:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  F_employement= pd.read_csv("Data.csv")

In [ ]:
F_employement = F_employement[(F_employement['yearBirth'] >= 1950) & (F_employement['yearBirth'] <= 2007)]

In [ ]:
F_employement = F_employement[F_employement['FemaleFlag'] != 0]

In [ ]:
# Ensure the DataFrame includes all rows by checking the total number of rows before and after the split
total_rows_before_split = F_employement.shape[0]

split_value = 1489039200
# Perform the split again to include the clarification
higher_df = F_employement[F_employement['api_applications_created'] >= split_value]
lower_df = F_employement[F_employement['api_applications_created'] < split_value]

# Verify that all rows are included in the split
total_rows_after_split = higher_df.shape[0] + lower_df.shape[0]

total_rows_before_split, total_rows_after_split

#higher_df.head(50)
lower_df.head(50)

,id,client_id,job_id,fid,title,date_of_posting,job_role,api_job_gender,year_of_passing_from,year_of_passing_to,...,SolvencyRatio,OperatingRevenue,OperatingProfitPerShare,EarningsPerShare,NetIncome,P_LBeforeTax,ShareholdersFunds,TotalAssets,MarketCap,PriceEarningsRatio_Avg
1,518735632,500004,198902,16166171,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
10,512653355,500004,198902,15672655,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
11,524238685,500004,198902,15408898,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
14,515157283,500004,198902,13696218,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
17,525234025,500004,198902,15525067,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
19,517995945,500004,198902,16099366,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
26,520505241,500004,198902,15202416,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
27,514169807,500004,198902,15953210,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
36,512768314,500004,198902,15694346,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
38,520990388,500004,198902,16338150,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
39,520256558,500004,198902,16008134,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
40,526283007,500004,198902,16403423,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
41,512320695,500004,198902,15128640,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
43,514270639,500004,198902,16079042,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
44,515550962,500004,198902,16011429,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
48,514273201,500004,198902,14337259,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
50,512769037,500004,198902,15942998,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
53,528970180,500004,198902,15665494,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
55,514531312,500004,198902,16217240,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
58,512409049,500004,198902,2833374,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
63,514407679,500004,198902,16101790,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
65,520421442,500004,198902,16317406,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
66,529481277,500004,198902,2200659,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
67,524957777,500004,198902,15076143,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
68,521556168,500004,198902,14692641,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
70,520342411,500004,198902,13682127,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
78,526342983,500004,198902,16400723,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
84,512293117,500004,198902,13902434,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
85,514400869,500004,198902,16060314,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
86,512482220,500004,198902,13678830,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
90,527546482,500004,198902,15629120,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
93,520115388,500004,198902,3186818,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
94,512468484,500004,198902,16079712,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
95,514496214,500004,198902,14663562,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
96,514477908,500004,198902,16215109,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
97,514401228,500004,198902,2464998,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
102,514561677,500004,198902,14663099,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
108,520342357,500004,198902,16329523,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
109,529129303,500004,198902,14567446,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
111,518334546,500004,198902,13893412,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
112,514137272,500004,198902,16203022,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
114,514117115,500004,198902,16194808,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
115,520980492,500004,198902,15655348,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
118,512509366,500004,198902,16153040,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
122,527502679,500004,198902,15340735,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
123,529123967,500004,198902,15110985,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
125,514437527,500004,198902,15992835,CLOUD ENGINEER,1464978601,13,3,2010.0,2015.0,...,-13.416,48238000.0,2.299,1.459,2496000.0,3761000.0,-3889000.0,28987000.0,24790.5880,8.496
129,471514933,500006,147573,14361326,ASSOCIATE QUALITY ENGINEER,1448994601,13,-1,NaN,NaN,...,58.840,556371.0,2.210,1.416,103475.0,162841.0,195492.0,332243.0,4834.6636,40.800
131,471514925,500006,147573,14313625,ASSOCIATE QUALITY ENGINEER,1448994601,13,-1,NaN,NaN,...,58.840,556371.0,2.210,1.416,103475.0,162841.0,195492.0,332243.0,4834.6636,40.800
132,472446696,500006,147573,14077564,ASSOCIATE QUALITY ENGINEER,1448994601,13,-1,NaN,NaN,...,58.840,556371.0,2.210,1.416,103475.0,162841.0,195492.0,332243.0,4834.6636,40.800

In [ ]:
X = higher_df[['yearBirth', 'course_type', 'job_role']]

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Assuming 'higher_df' is your DataFrame with the combined dataset

# Filling missing numeric data with the median of the respective column
higher_df.fillna(higher_df.median(), inplace=True)

# Selecting features and the target variable
X = higher_df.drop(['id', 'client_id', 'job_id', 'fid', 'title', 'date_of_posting', 'call_letter_date', 'bd_lnkdin_co_profile_emp2', 'CalLetterFlag'], axis=1)
y = higher_df['CalLetterFlag']

# Convert categorical variables into dummy variables. This step is crucial to convert all text data into numeric form.
X = pd.get_dummies(X, drop_first=True)

# Filling any remaining missing values with 0 (after potential median imputation)
X.fillna(0, inplace=True)

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardizing the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initializing and fitting the logistic regression model with class weights for balancing
model = LogisticRegression(class_weight='balanced')
model.fit(X_train_scaled, y_train)

# Making predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluating the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Printing the evaluation results
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

<ipython-input-18-ffb945781204>:10: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  higher_df.fillna(higher_df.median(), inplace=True)
<ipython-input-18-ffb945781204>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  higher_df.fillna(higher_df.median(), inplace=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy: 0.7395575021738431
Confusion Matrix:
[[64954 23538]
 [  723  3938]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.73      0.84     88492
           1       0.14      0.84      0.25      4661

    accuracy                           0.74     93153
   macro avg       0.57      0.79      0.54     93153
weighted avg       0.95      0.74      0.81     93153

In [ ]:
filename = "model.pickle"
pickle.dump(model, open(filename, 'wb'))
loaded_model = pickle.load(open(filename, 'rb'))

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Assuming 'higher_df' is your DataFrame with the combined dataset

# Filling missing numeric data with the median of the respective column
lower_df.fillna(lower_df.median(), inplace=True)

# Selecting features and the target variable
X = lower_df.drop(['id', 'client_id', 'job_id', 'fid', 'title', 'date_of_posting', 'call_letter_date', 'bd_lnkdin_co_profile_emp2', 'CalLetterFlag'], axis=1)
y = lower_df['CalLetterFlag']

# Convert categorical variables into dummy variables. This step is crucial to convert all text data into numeric form.
X = pd.get_dummies(X, drop_first=True)

# Filling any remaining missing values with 0 (after potential median imputation)
X.fillna(0, inplace=True)

# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Standardizing the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initializing and fitting the logistic regression model with class weights for balancing
model1 = LogisticRegression(class_weight='balanced')
model1.fit(X_train_scaled, y_train)

# Making predictions on the test set
y_pred = model1.predict(X_test_scaled)

# Evaluating the model1
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Printing the evaluation results
print(f"Accuracy: {accuracy}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(class_report)

<ipython-input-20-2c75e89ce156>:10: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  lower_df.fillna(lower_df.median(), inplace=True)
<ipython-input-20-2c75e89ce156>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lower_df.fillna(lower_df.median(), inplace=True)

Accuracy: 0.7472087949694144
Confusion Matrix:
[[33506 11602]
 [  217  1429]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.74      0.85     45108
           1       0.11      0.87      0.19      1646

    accuracy                           0.75     46754
   macro avg       0.55      0.81      0.52     46754
weighted avg       0.96      0.75      0.83     46754

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
filename = "model1.pickle"
pickle.dump(model1, open(filename, 'wb'))
loaded_model = pickle.load(open(filename, 'rb'))

In [ ]:
type(X_test)

pandas.core.frame.DataFrame

In [ ]:
print(X_test)

         job_role  api_job_gender  year_of_passing_from  year_of_passing_to  \
279973         13               3                2015.0              2016.0
35940          13               3                2016.0              2016.0
832084         13               3                2016.0              2016.0
41493          13               3                2016.0              2016.0
1149515        13               3                2016.0              2016.0
...           ...             ...                   ...                 ...
43282          13              -1                2015.0              2016.0
637059         13               3                2016.0              2016.0
483572         13               3                2015.0              2016.0
669509         13               3                2015.0              2016.0
1103290        13               3                2014.0              2015.0

         hq_marks_percentage_from  hq_marks_percentage_to  hq_marks_cgpa_from  \
279973                       60.0                   100.0                 6.0
35940                        65.0                   100.0                 6.5
832084                       60.0                   100.0                 6.0
41493                        65.0                   100.0                 6.5
1149515                      60.0                   100.0                 6.0
...                           ...                     ...                 ...
43282                        60.0                   100.0                 6.0
637059                       60.0                   100.0                 6.0
483572                       60.0                   100.0                 6.0
669509                       60.0                   100.0                 6.0
1103290                      60.0                   100.0                 6.0

         hq_marks_cgpa_to  api_applications_created  users_city_id  ...  \
279973               10.0                1477039035             98  ...
35940                10.0                1482306703             88  ...
832084               10.0                1479288643             65  ...
41493                10.0                1482932939            109  ...
1149515              10.0                1462857416             98  ...
...                   ...                       ...            ...  ...
43282                10.0                1448767686             65  ...
637059               10.0                1479191345            125  ...
483572               10.0                1463494857            147  ...
669509               10.0                1468476911             75  ...
1103290              10.0                1459351838             65  ...

         NetIncome  P_LBeforeTax  ShareholdersFunds  TotalAssets  MarketCap  \
279973   2623.5190     4036.8237         13840.5340    29908.543  9235.4424
35940    2623.5190     4726.6870         16118.1370   147549.450  9235.4424
832084   1973.1255     2753.8333          5070.3545    11697.640  9235.4424
41493    2623.5190     4726.6870         16118.1370   147549.450  9235.4424
1149515  2623.5190     4726.6870         16118.1370   147549.450  9235.4424
...            ...           ...                ...          ...        ...
43282    2623.5190     4726.6870         16118.1370   147549.450  9235.4424
637059   2623.5190     4726.6870         16118.1370   147549.450  9235.4424
483572   2623.5190     4726.6870         16118.1370   147549.450  9235.4424
669509   1493.4344     2235.5078          7566.8384    12297.113  9235.4424
1103290  5503.0313     7774.1460        207191.4400   559886.380   291.9559

         PriceEarningsRatio_Avg  applier_type_f  applier_type_r  \
279973                   16.047               1               0
35940                    16.047               1               0
832084                   16.047               0               0
41493                    16.047               1               0
1149515                  16.047               1               0
...                         ...             ...             ...
43282                    16.047               1               0
637059                   16.047               1               0
483572                   16.047               1               0
669509                   16.047               1               0
1103290                  50.537               1               0

         course_type_others_category  course_type_pg
279973                             0               1
35940                              0               0
832084                             0               0
41493                              0               0
1149515                            0               0
...                              ...             ...
43282                              0               0
637059                             0               0
483572                             0               0
669509                             0               0
1103290                            0               1

[46754 rows x 49 columns]